main:
  tmppath: ../tmp/                                              # Path for temporary files
  logging:
    system: ../log/system.log                                   # Path to System-Log
    request: ../log/requests.log                                # Path to Request-Log
    error: ../log/error.log                                     # Path to Error-Log
  dateformat: 'd.m.y H:i:s'                                     # Format for timestamps - See php.net/date for more information
  debugmode: false                                              # Enable debugging (debugging can also be enabled for a single run by setting the option --debug)
  user: www-data                                                # *NIX-User under which Pancake should run
  group: www-data                                               # *NIX-Group under which Pancake should run
  listenports:                                                  # List of ports to listen on (Recommended for HTTP: 80)
    - 80
  ipv4:                                                         # IPv4 network interfaces to listen on (use 0 to listen on all available interfaces)
    - 0
  ipv6:                                                         # IPv6 network interfaces to listen on (use ::0 to listen on all available interfaces)
    - ::0
  requestworkers: 4                                             # Amount of RequestWorkers to run
  readtimeout: 200000                                           # Timelimit until Pancake will decline a request in µs
  exposepancake: true                                           # If true, Pancake will send a "Server"-Header with Information about Pancake
  sharedmemory: 10000000                                        # Size of SharedMemory in Bytes
  sizeprefix: bin                                               # "si" or "bin" - SI: 1000 Byte = 1 Kilobyte - Binary: 1024 Byte = 1 Kibibyte
  allowhead: true                                               # Whether to allow the "HEAD"-requestmethod
  allowtrace: true                                              # Whether to allow the "TRACE"-requestmethod
  allowoptions: true                                            # Whether to allow the "OPTIONS"-requestmethod
  requestworkerlimit: 50000                                     # Limit of requests a RequestWorker may process until it has to be restarted (0 for no limit)
  maxconcurrent: 0                                              # Limit of concurrent connections a RequestWorker may hold open (0 for no limit)
  workerboottime: 5                                             # The upper timelimit for a worker to boot (raise this when you're for example caching files that take long to load)
include:                                                        # Additional configuration-files to include
  - ../conf/vhosts/
  - ../conf/mime.yml