main:
  tmppath: /usr/local/Pancake/tmp/                              # Path for temporary files
  logging:
    system: /usr/local/Pancake/log/system.log                   # Path to System-Log
    request: /usr/local/Pancake/log/requests.log                # Path to Request-Log
    error: /usr/local/Pancake/log/error.log                     # Path to Error-Log
  dateformat: 'd.m.y H:i:s'                                     # Format for timestamps - See php.net/date for more information
  debugmode: false                                              # Enable debugging
  user: www-data                                                # *NIX-User under which Pancake should run
  group: www-data                                               # *NIX-Group under which Pancake should run
  listenports:                                                  # List of ports to listen on (Recommended for HTTP: 80)
    - 80
  ipv4:                                                         # IPv4 network interfaces to listen on (use 0 to listen on all available interfaces)
    - 0
  ipv6:                                                         # IPv6 network interfaces to listen on (use 0 to listen on all available interfaces)
    - 0
  requestworkers: 10                                            # Amount of RequestWorkers to run
  readtimeout: 200000                                           # Timelimit until Pancake will decline a request in µs
  exposepancake: true                                           # If true, Pancake will send a "Server"-Header with Information about Pancake
  sharedmemory: 10000000                                        # Size of SharedMemory in Bytes
  sizeprefix: bin                                               # "si" or "bin" - SI: 1000 Byte = 1 Kilobyte - Binary: 1024 Byte = 1 Kibibyte
  allowhead: true                                               # Whether to allow the "HEAD"-requestmethod
  allowtrace: true                                              # Whether to allow the "TRACE"-requestmethod
  allowoptions: true                                            # Whether to allow the "OPTIONS"-requestmethod
include:                                                        # Additional configuration-files to include
  - /usr/local/Pancake/conf/vhosts/
  - /usr/local/Pancake/conf/mime.yml