vhosts:
  default:                                                      # Name of the vHost
    docroot: /var/vhosts/pancake/default/                       # Path to DocumentRoot
    listen:                                                     # Hosts to listen on
      - pp3345.de:90
      - www.pp3345.de:90
      - 84.200.43.132:90
      - pp3345.de:100
      - www.pp3345.de:100
      - 84.200.43.132:100
      - 127.0.0.1:100
      - 127.0.0.1:90
    phpworkers: 3                                               # Amount of PHP-Workers to run
    index:                                                      # List of files allowed as directory-indexes
      - index.htm
      - index.html
      - index.php